## Building Target Platforms

To build, you require specific versions of Java and Maven. Also, there is some Maven setup. 
The https://community.jboss.org/wiki/HowToBuildJBossToolsWithMaven3[How to Build JBoss Tools with Maven 3]
document will guide you through that setup.

This command will run the build, but will NOT download the contents of the target platform to disk:

    $ mvn clean verify

If you want to download the contents of the target platform to disk, do this:

    $ mvn clean verify -Pmultiple2repo

If you want to run the build and fetch source bundles at the same time as other bundles are being resolved, do this:

    $ mvn clean verify -Pmultiple2repo -Dmirror-target-to-repo.includeSources=true

If you want to run the build and not fail if there's a problem w/ validation, do this:

    $ mvn clean verify -Pmultiple2repo -Dvalidate-target-platform.failOnError=false

If you just want to check if things compiles/builds you can run:

    $ mvn clean verify -Pmultiple2repo -DskipTest=true

But *do not* push changes without having the new and existing unit tests pass!


## Updating versions of IUs in .target files

When moving from one version of the target to another, the steps are:

0. Bump the target platform versions contained in all pom.xml and *.target files.

1. Update the URLs contained in jbosstools-multiple.target and jbdevstudio-multiple.target (by hand). Check in changes (but do not push to master).

2. Regenerate the IU versions, using <a href="https://github.com/jbosstools/jbosstools-maven-plugins/wiki">org.jboss.tools.tycho-plugins:target-platform-utils</a>, and validate results.

3. When the script below is done, follow the <a href="https://github.com/jbosstools/jbosstools-devdoc/blob/master/building/target_platforms/target_platforms_updates.adoc">release guidelines</a> for how to announce target platform changes.</li>

4. Check in updated target files &amp; push to the branch.

[source,bash]
----
# TODO: migrate this scriptlet to a new repo and store as a bash script, in order to better keep these in sync
# https://github.com/jbosstools/jbosstools-discovery/tree/master/#updating-versions-of-ius-in-target-files
# https://github.com/jbosstools/jbosstools-target-platforms/tree/master/#updating-versions-of-ius-in-target-files
# https://github.com/jbosstools/jbosstools-target-platforms/tree/4.40.x/#updating-versions-of-ius-in-target-files

# point BASEDIR to where you have these sources checked out
BASEDIR=$HOME/jbosstools-discovery; # or, just do this:
BASEDIR=`pwd`

# set path to where you have the latest compatible Eclipse bundle stored locally
ECLIPSEZIP=${HOME}/tmp/Eclipse_Bundles/eclipse-jee-luna-M7-linux-gtk-x86_64.tar.gz

# set URL(s) for JBT / JBT Target so that all Central deps can be resolved; for more than one, separate w/ commas
UPSTREAM_SITE=file://$HOME/tru/jbosstools-target-platforms/jbosstools/multiple/target/jbosstools-multiple.target.repo/,http://download.jboss.org/jbosstools/updates/nightly/core/master/
# for JBDS tests, use UPSTREAM_SITE=file://$HOME/tru/jbosstools-target-platforms/jbdevstudio/multiple/target/jbdevstudio-multiple.target.repo/,http://www.qa.jboss.com/binaries/RHDS/builds/staging/devstudio.product_master/all/repo/

# set path to where you have the latest p2diff executable installed
P2DIFF=${HOME}/tmp/p2diff/p2diff

NOW=`date +%F_%H-%M`

for PROJECT in jbtcentral jbtearlyaccess; do

  if [[ -d ${BASEDIR}/${PROJECT} ]]; then WORKSPACE=${BASEDIR}/${PROJECT}; else WORKSPACE=${BASEDIR}; fi
  if [[ -d ${BASEDIR}/${PROJECT}target ]]; then WORKSPACE=${BASEDIR}/${PROJECT}target; else WORKSPACE=${BASEDIR}; fi

  # Step 0: move the existing target platform folder to a new path, so that it can be p2diff'd against the one you're about to build
  # TODO: remember to clean these out
  if [[ -d ${WORKSPACE}/multiple/target/${PROJECT}-multiple.target.repo/ ]]; then
    mv ${WORKSPACE}/multiple/target/${PROJECT}-multiple.target.repo/ /tmp/${PROJECT}-multiple.target.repo_${NOW} && touch /tmp/${PROJECT}-multiple.target.repo_${NOW}
  fi

  # Step 1: Merge changes in new target file to actual target file
  pushd ${WORKSPACE}/multiple && mvn -U org.jboss.tools.tycho-plugins:target-platform-utils:0.19.0-SNAPSHOT:fix-versions -DtargetFile=${PROJECT}-multiple.target && rm -f ${PROJECT}-multiple.target ${PROJECT}-multiple.target_update_hints.txt && mv -f ${PROJECT}-multiple.target_fixedVersion.target ${PROJECT}-multiple.target && popd

  # Step 2: Resolve the new 'multiple' target platform and verify it is self-contained by building the 'unified' target platform too
  # TODO: if you removed IUs, be sure to do a `mvn clean install`, rather than just a `mvn install`; process will be much longer but will guarantee metadata is correct 
  pushd ${WORKSPACE} && mvn install -Pmultiple2repo -DtargetRepositoryUrl=file://${WORKSPACE}/multiple/target/${PROJECT}-multiple.target.repo/ -Dmirror-target-to-repo.includeSources=true && popd

  # Step 3: Install the new target platform into a clean Eclipse JEE bundle to verify if everything can be installed
  INSTALLDIR=/tmp/${PROJECT}target-install-test
  INSTALLSCRIPT=/tmp/installFromTarget.sh
  rm -fr ${INSTALLDIR} && mkdir -p ${INSTALLDIR}
  pushd ${INSTALLDIR}
    echo "Unpack ${ECLIPSEZIP} into ${INSTALLDIR} ..." && tar xzf ${ECLIPSEZIP}
    echo "Fetch install script to ${INSTALLSCRIPT} ..." && wget -q --no-check-certificate -N https://raw.githubusercontent.com/jbosstools/jbosstools-build-ci/master/util/installFromTarget.sh -O ${INSTALLSCRIPT} && chmod +x ${INSTALLSCRIPT} 
    echo "Install..."
    if [[ ${UPSTREAM_SITE} ]]; then
      ${INSTALLSCRIPT} -ECLIPSE ${INSTALLDIR}/eclipse -INSTALL_PLAN ${UPSTREAM_SITE},file://${WORKSPACE}/multiple/target/${PROJECT}-multiple.target.repo/ | tee ${INSTALLSCRIPT}_log_${PROJECT}_${NOW}.txt; 
    else
      ${INSTALLSCRIPT} -ECLIPSE ${INSTALLDIR}/eclipse -INSTALL_PLAN file://${WORKSPACE}/multiple/target/${PROJECT}-multiple.target.repo/ | tee ${INSTALLSCRIPT}_log_${PROJECT}_${NOW}.txt; 
    fi
    cat ${INSTALLSCRIPT}_log_${PROJECT}_${NOW}.txt | egrep -i -A2 "IllegalArgumentException|Could not resolve|error|Unresolved requirement|could not be found|FAILED|Missing|Only one of the following|being installed|Cannot satisfy dependency"; if [[ "$?" == "0" ]]; then break; fi
  popd

  # Step 4: produce p2diff report
  ${P2DIFF} /tmp/${PROJECT}-multiple.target.repo_${NOW} file://${WORKSPACE}/multiple/target/${PROJECT}-multiple.target.repo/ | tee /tmp/p2diff_log_${PROJECT}_${NOW}.txt

done


----