== The JBoss Tools Central Discovery project

=== Summary

The _JBoss Tools Central Discovery_ project provides a mechanism for building a plugin jar, directory.xml file, and a composite update site used by https://github.com/jbosstools/jbosstools-central[JBoss Central].

=== Install

To use a Discovery site, you need to first install JBoss Central, which is part of http://jboss.org/tools[JBoss Tools]. Central will then connect to a Discovery site via the default (or other) directory.xml file, which will link to the plugin jar, which will in turn list a catalogue of available updates, installable from a composite site.

=== Use

Both the URL for the directory.xml and the URL used within the plugin (to which the directory.xml refers) can be overridden via the commandline when launching Eclipse (or JBoss Developer Studio). Via commandline (or inside your eclipse.ini / jbdevstudio.ini file), you can specify these arguments:

[source,bash]
----
eclipse -vmargs \
  -Djboss.discovery.directory.url=http://download.jboss.org/jbosstools/discovery/nightly/core/master/jbosstools-directory.xml
  -Djboss.discovery.site.url=http://download.jboss.org/jbosstools/discovery/nightly/core/master/
  -Djboss.discovery.earlyaccess.site.url=http://download.jboss.org/jbosstools/discovery/nightly/earlyaccess/master/
----

or

[source,bash]
----
jbdevstudio -vmargs \
  -Djboss.discovery.directory.url=https://devstudio.redhat.com/updates/8.0-staging/devstudio-directory.xml
  -Djboss.discovery.site.url=https://devstudio.redhat.com/updates/8.0-staging/central/core/
  -Djboss.discovery.earlyaccess.site.url=https://devstudio.redhat.com/updates/8.0-staging/central/earlyaccess/
----


=== Build target platform(s) locally

See https://github.com/jbosstools/jbosstools-devdoc/blob/master/building/target_platforms/target_platforms_updates.adoc#build-target-platforms-locally[Build target platform(s) locally]

To verify local changes to a target platform, see:

https://github.com/jbosstools/jbosstools-build-ci/blob/master/util/verifyTarget.sh


=== Update versions of IUs in the .target files

See https://github.com/jbosstools/jbosstools-devdoc/blob/master/building/target_platforms/target_platforms_updates.adoc#update-versions-of-ius-in-the-target-files[Update versions of IUs in the .target files]


=== Build Discovery Sites

See link:README.building.discovery.sites.adoc[]


=== Get the code

Need help cloning this repo? See link:README.contributing.adoc[Get the code].

=== Want to contribute? 

See link:README.contributing.adoc[Contributing].