## Build a local site

To build _JBoss Tools Discovery_ requires specific versions of Java and
Maven. Also, there is some Maven setup. The https://community.jboss.org/wiki/HowToBuildJBossToolsWithMaven3[How to Build JBoss Tools with Maven 3]
document will guide you through that setup.

You must pass in the following commandline arguments (target platform URL is calculated from parent pom's TARGET_PLATFORM_VERSION):

[NOTE]
====
In this example, build against master branch update site.
====

[source,bash]
----
mvn clean install -f jbosstools/org.jboss.tools.central.discovery/pom.xml -DBUILD_NUMBER=999 \
  -DUPDATE_SITE=http://download.jboss.org/jbosstools/oxygen/snapshots/updates/core/master/ \
  -DEXTRAS_SITE=http://download.jboss.org/jbosstools/oxygen/snapshots/updates/central/master/,http://download.jboss.org/jbosstools/targetplatforms/jbtcentraltarget/4.73.0.Final-SNAPSHOT/REPO/
----

or

[source,bash]
----
mvn clean install -f devstudio/com.jboss.devstudio.central.discovery/pom.xml -DBUILD_NUMBER=999 \
  -DUPDATE_SITE=https://devstudio.redhat.com/11/snapshots/updates/core/master/ \
  -DEXTRAS_SITE=https://devstudio.redhat.com/11/snapshots/updates/central/master/,https://devstudio.redhat.com/targetplatforms/jbtcentraltarget/4.73.0.Final-SNAPSHOT/REPO/
----

Repeat for Early Access sites (using 2 EXTRAS_SITE URLs so the resulting site can resolve both Core and Early Access content):

[NOTE]
====
In this example, build against stable branch update site.
====

[source,bash]
----
mvn clean install -f jbosstools/org.jboss.tools.central.discovery.earlyaccess/pom.xml -DBUILD_NUMBER=999 \
  -DUPDATE_SITE=http://download.jboss.org/jbosstools/oxygen/snapshots/updates/core/master/ \
  -DEXTRAS_SITE=http://download.jboss.org/jbosstools/oxygen/snapshots/updates/central/master/,http://download.jboss.org/jbosstools/targetplatforms/jbtcentraltarget/4.73.0.Final-SNAPSHOT/REPO/,http://download.jboss.org/jbosstools/oxygen/snapshots/updates/earlyaccess/master/,http://download.jboss.org/jbosstools/targetplatforms/jbtearlyaccesstarget/4.73.0.Final-SNAPSHOT/REPO/
----

or

[source,bash]
----
mvn clean install -f devstudio/com.jboss.devstudio.central.discovery.earlyaccess/pom.xml -DBUILD_NUMBER=999 \
  -DUPDATE_SITE=https://devstudio.redhat.com/11/snapshots/updates/core/master/ \
  -DEXTRAS_SITE=https://devstudio.redhat.com/11/snapshots/updates/central/master/,https://devstudio.redhat.com/targetplatforms/jbtcentraltarget/4.73.0.Final-SNAPSHOT/REPO/,https://devstudio.redhat.com/11/snapshots/updates/earlyaccess/master/,https://devstudio.redhat.com/targetplatforms/jbtearlyaccesstarget/4.73.0.Final-SNAPSHOT/REPO/
----

## Test a local site

0. Run a local web server, so you can access the directory.xml via an http:// URL. You have many options for this - recommended is https://raw.githubusercontent.com/elonen/nanohttpd/nanohttpd-for-java1.1/NanoHTTPD.java[NanoHTTPD].

[source,bash]
----
su
# this is the single-file version of nanohttpd that works w/ JDK 1.1 and higher
cd /tmp; wget https://raw.githubusercontent.com/elonen/nanohttpd/nanohttpd-for-java1.1/NanoHTTPD.java
# assuming sources checked out into /home/user/jbosstools-discovery/
javac NanoHTTPD.java; java NanoHTTPD -d /home/user/jbosstools-discovery/ -p 8080
----

1. Build target platforms for Central - Core and Early Access. If you want to do more validation, see link:README.building.target-platforms.adoc[]

[source,bash]
----
for d in jbtcentral jbtearlyaccess; do
  pushd ${d}target
    BASEDIR=`pwd`
    # Merge changes in new target file to actual target file
    pushd multiple && mvn -U org.jboss.tools.tycho-plugins:target-platform-utils:1.1.0:fix-versions -DtargetFile=${d}-multiple.target && rm -f ${d}-multiple.target ${d}-multiple.target_update_hints.txt && mv -f ${d}-multiple.target_fixedVersion.target ${d}-multiple.target && popd
    # Resolve the new 'multiple' target platform and verify it is self-contained by building it
    mvn -U install -DtargetRepositoryUrl=file://${BASEDIR}/multiple/target/${d}-multiple.target.repo/
  popd
done
----

2. Build Discovery plugin + site:

[source,bash]
----
mvn clean install -f jbosstools/org.jboss.tools.central.discovery/pom.xml \
  -DUPDATE_SITE=http://download.jboss.org/jbosstools/oxygen/snapshots/updates/core/master/ \
  -DEXTRAS_SITE=http://download.jboss.org/jbosstools/oxygen/snapshots/updates/central/master/,http://localhost:8080/jbtcentraltarget/multiple/target/jbtcentral-multiple.target.repo/
----

or

[source,bash]
----
mvn clean install -f devstudio/com.jboss.devstudio.central.discovery/pom.xml \
  -DUPDATE_SITE=https://devstudio.redhat.com/11/snapshots/updates/core/master/ \
  -DEXTRAS_SITE=https://devstudio.redhat.com/11/snapshots/updates/central/master/,http://localhost:8080/jbtcentraltarget/multiple/target/jbtcentral-multiple.target.repo/
----

Repeat for Early Access plugin + site (using 2 EXTRAS_SITE URLs so the resulting site can resolve both Core and Early Access content):

[source,bash]
----
mvn clean install -f jbosstools/org.jboss.tools.central.discovery.earlyaccess/pom.xml \
  -DUPDATE_SITE=http://download.jboss.org/jbosstools/oxygen/snapshots/updates/core/master/ \
  -DEXTRAS_SITE=http://download.jboss.org/jbosstools/oxygen/snapshots/updates/central/master/,http://download.jboss.org/jbosstools/oxygen/snapshots/updates/earlyaccess/master/,http://localhost:8080/jbtcentraltarget/multiple/target/jbtcentral-multiple.target.repo/,http://localhost:8080/jbtearlyaccesstarget/multiple/target/jbtearlyaccess-multiple.target.repo/
----

or

[source,bash]
----
mvn clean install -f devstudio/com.jboss.devstudio.central.discovery.earlyaccess/pom.xml \
  -DUPDATE_SITE=https://devstudio.redhat.com/11/snapshots/updates/core/master/ \
  -DEXTRAS_SITE=https://devstudio.redhat.com/11/snapshots/updates/central/master/,https://devstudio.redhat.com/11/snapshots/updates/earlyaccess/master/,http://localhost:8080/jbtcentraltarget/multiple/target/jbtcentral-multiple.target.repo/,http://localhost:8080/jbtearlyaccesstarget/multiple/target/jbtearlyaccess-multiple.target.repo/
----

3. Install Eclipse (eg., 4.7 Oxygen JEE bundle)

4. Launch Eclipse (or Devstudio):

[source,bash]
----
./eclipse -vmargs \
  -Djboss.discovery.directory.url=http://localhost:8080/jbosstools/org.jboss.tools.central.discovery.earlyaccess/target/discovery-site/jbosstools-directory.xml \
  -Djboss.discovery.site.url=http://localhost:8080/jbosstools/org.jboss.tools.central.discovery.earlyaccess/target/discovery-site/ \
  -Djboss.discovery.earlyaccess.site.url=http://localhost:8080/jbosstools/org.jboss.tools.central.discovery.earlyaccess/target/discovery-site/
----

or

[source,bash]
----
./devstudio -vmargs \
  -Djboss.discovery.directory.url=http://localhost:8080/devstudio/com.jboss.devstudio.central.discovery.earlyaccess/target/discovery-site/devstudio-directory.xml \
  -Djboss.discovery.site.url=http://localhost:8080/devstudio/com.jboss.devstudio.central.discovery.earlyaccess/target/discovery-site/ \
  -Djboss.discovery.earlyaccess.site.url=http://localhost:8080/devstudio/com.jboss.devstudio.central.discovery.earlyaccess/target/discovery-site/
----

5. Install Central:

* Install JBoss Community Central feature from
** http://localhost:8080/jbosstools/org.jboss.tools.central.discovery/target/discovery-site/
*** or
* Install Red Hat Developer Studio (Core Features) feature from
** http://localhost:8080/devstudio/com.jboss.devstudio.central.discovery/target/discovery-site/

6. Restart. Review Central's Software/Update tab. For Early Access connectors, scroll to the bottom of the list of connectors and enable the Early Access Features checkbox. Choose connectors/feature groups to install.


## Test a site built w/ Jenkins

1. Install Eclipse (eg., 4.7 Oxygen JEE bundle)

2. Launch Eclipse:

[source,bash]
----
./eclipse -vmargs \
  -Djboss.discovery.directory.url=http://download.jboss.org/jbosstools/oxygen/snapshots/updates/discovery.central/master/jbosstools-directory.xml \
  -Djboss.discovery.site.url=http://download.jboss.org/jbosstools/oxygen/snapshots/updates/discovery.central/master/ \
  -Djboss.discovery.earlyaccess.site.url=http://download.jboss.org/jbosstools/oxygen/snapshots/updates/discovery.earlyaccess/master/
----

3. Install JBoss Community Central feature from http://download.jboss.org/jbosstools/oxygen/snapshots/updates/discovery.central/master/

4. Restart. Review Central > Software/Update tab. For Early Access connectors, scroll to the bottom of the list of connectors and enable the Early Access Features checkbox. Choose connectors/feature groups to install.

5. Or, launch Devstudio like this:

[source,bash]
----
./devstudio -vmargs \
  -Djboss.discovery.directory.url=https://devstudio.redhat.com/11/snapshots/updates/discovery.central/master/devstudio-directory.xml \
  -Djboss.discovery.site.url=https://devstudio.redhat.com/11/snapshots/updates/discovery.central/master/ \
  -Djboss.discovery.earlyaccess.site.url=https://devstudio.redhat.com/11/snapshots/updates/discovery.earlyaccess/master/
----

Instead of the latest master build, you can also point Eclipse / Devstudio at more stable Central sites:

* The current released milestone URLs for JBT/Devstudio are:

** http://download.jboss.org/jbosstools/oxygen/development/updates/discovery.central/4.6.0.*/jbosstools-directory.xml
** https://devstudio.redhat.com/11/development/updates/discovery.central/12.0.0.*/devstudio-directory.xml

* The staging URLs are:

** http://download.jboss.org/jbosstools/oxygen/staging/updates/discovery.central/
** http://download.jboss.org/jbosstools/oxygen/staging/updates/discovery.earlyaccess/

** https://devstudio.redhat.com/11/staging/updates/discovery.central/
** https://devstudio.redhat.com/11/staging/updates/discovery.earlyaccess/

* The master branch URLs are:

**  http://download.jboss.org/jbosstools/oxygen/snapshots/updates/discovery.central/master/
**  http://download.jboss.org/jbosstools/oxygen/snapshots/updates/discovery.earlyaccess/master/

**  https://devstudio.redhat.com/11/snapshots/updates/discovery.central/master/
**  https://devstudio.redhat.com/11/snapshots/updates/discovery.earlyaccess/master/

